// src/app/layout.tsx (NO cambiar)
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AURUM Sound',
  keywords: ['aurum', 'sound', 'headphones', 'audio', 'premium'],
  authors: [{ name: 'AURUM Sound', url: 'https://aurumsound.com' }],
  creator: 'AURUM Sound',
  description: 'Generated by ',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}